Make git-review handle pulling review patches, too.
The 'push' subcommand is required to emulate the old functionality, so this

    git review

becomes

    git review push

To pull in another review just make sure you have the right 'changes' remote and use
the 'start' subcommand:

    git review start 45

Once you're done reviewing it, just use the 'reset' subcommand:

    git review reset

diff --git a/bin/git-review b/bin/git-review
--- a/bin/git-review
+++ b/bin/git-review
@@ -3,52 +3,12 @@
 CURRENT=$(git symbolic-ref -q HEAD || git rev-parse HEAD)
 CURRENT=${CURRENT#refs/heads/}
 
+this=$(basename "$0")
+
 # default settings
 explain=false
 verbose=true
 run=true
-
-printUsage() {
-  echo "usage: $0 [options] [change number]"
-  echo
-  echo "  -h  --help                  Show this message"
-  echo "  -v  --verbose               Show all commands before running them (default: on)"
-  echo "  -q  --quiet                 Don't display commands before running them (default: off)"
-  echo "  -e  --explain  --dry-run    Don't actually run commands (default: off)"
-  echo
-  echo "git-review uploads a single change to gerrit and then removes that change from master."
-  echo "If you pass it a change number, it will replace that change instead of making a new one."
-}
-
-for arg in "$@"; do
-  case $arg
-  in
-    -e | --explain | --dry-run)
-      explain=true
-      verbose=true
-      run=false
-      ;;
-    -v | --verbose)
-      verbose=true
-      ;;
-    -q | --quiet)
-      verbose=false
-      ;;
-    -h | --help)
-      printUsage
-      exit
-      ;;
-    *)
-      if [[ "$change" != "" ]]; then
-        echo "$0: already given a change number ($change), but got another ($arg)"
-        printUsage
-        exit 1
-      else
-        change=$arg
-      fi
-      ;;
-  esac
-done
 
 # colors
 RED="\033[0;31m"
@@ -83,8 +43,8 @@ git() {
 }
 
 no_changes () {
-	$GIT diff-index --quiet --cached HEAD -- &&
-	$GIT diff-files --quiet
+  $GIT diff-index --quiet --cached HEAD -- &&
+  $GIT diff-files --quiet
 }
 
 check_stash() {
@@ -93,43 +53,169 @@ check_stash() {
   fi
 }
 
-if [[ "$explain" == true ]]; then
-  echo "These are the commands that would be run:"
-fi
+printShortUsage() {
+  echo "Usage: $this [<options>] push [<change number>]"
+  echo "   or: $this [<options>] start <change number>"
+  echo "   or: $this [<options>] reset"
+}
+printUsage() {
+  printShortUsage
+  echo
+  echo "OPTIONS"
+  echo "  -h  --help                  Show this message"
+  echo "  -v  --verbose               Show all commands before running them (default: on)"
+  echo "  -q  --quiet                 Don't display commands before running them (default: off)"
+  echo "  -e  --explain  --dry-run    Don't actually run commands (default: off)"
+  echo
+  echo "DESCRIPTION"
+  echo "  $this assists in code reviews with gerrit, both pushing or pulling changesets to review."
+  echo
+  echo "  push [<change number>]"
+  echo "    Pushes a single patch to gerrit for review. If your HEAD is master, $this will"
+  echo "    reset master to origin/master after successfully pushing the changeset. If you are"
+  echo "    working on a topic branch, that branch will be left alone."
+  echo
+  echo "    Given a change number, the current patch will replace the existing one, following"
+  echo "    the same reset rules as above."
+  echo
+  echo "  start <change number>"
+  echo "    Applies the latest patch for the change at <change number> on top of master on a"
+  echo "    branch named for <change number>, allowing you to review the change."
+  echo
+  echo "  reset"
+  echo "    Removes the current change branch created by the 'start' subcommand and switches"
+  echo "    back to master."
+}
+
+
+pushReview() {
+  LOG=$($GIT log --pretty="format:%s" origin/master..HEAD)
+  CHANGESETS=$($GIT rev-list origin/master..HEAD | wc -l)
+  CHANGESETS=${CHANGESETS//[[:space:]]}
+
+  if [[ "$CHANGESETS" == "0" ]]; then
+    die "You have no changes to review. Are you on the right branch?"
+  elif [[ "$CHANGESETS" != "1" ]]; then
+    die "You have $CHANGESETS changes, but you should only push one at a time. Did you forget to squash your commits?"
+  fi
+
+  if [[ "$change" != "" ]]; then
+    change_args="origin HEAD:refs/changes/$change"
+  fi
+
+  git push $change_args ||
+    die "Could not push your changes for review. Perhaps you need to update first?"
+
+  if [[ "$CURRENT" == "master" ]]; then
+    git reset --hard origin/master ||
+      die "Could not reset your master branch to origin/master."
+  fi
+
+  if [[ "$run" == true ]]; then
+    if [[ "$CURRENT" == "master" ]]; then
+      good "Successfully pushed '$LOG' for review and reset master"
+    else
+      good "Successfully pushed '$LOG' for review"
+    fi
+  fi
+}
+
+# git review start 100
+startReview() {
+  $GIT remote show changes 2>/dev/null 1>&2 ||
+    die "In order to use $this to start a review, you need a 'changes' remote. Please add it before trying again."
+
+  # pick up the latest patch for the changeset we're reviewing
+  git fetch changes ||
+    die "Unable to fetch changes, please check your network connection"
+
+  change=$1
+  changeref=refs/remotes/changes/${change:(-2)}/$change
+  patchref=$($GIT rev-parse --symbolic-full-name --all | grep $changeref | sort --reverse | head -n1)
+
+  if [[ -z "$patchref" ]]; then
+    die "Unable to find a patch for ±$change"
+  fi
+
+  # create a new branch based on master to work in
+  branch=change$change
+  $GIT branch -D $branch 2>/dev/null 1>&2
+  git checkout -b $branch master ||
+    die "Unable to create a new branch '$branch'"
+
+  # apply the change to the new branch
+  git cherry-pick $patchref ||
+    die "Unable to apply ±$change on top of master"
+
+  if [[ "$run" == true ]]; then
+    good "Successfully cherry-picked ±$change so you can begin reviewing it"
+  fi
+}
+
+
+# git review reset
+resetReview() {
+  if [[ ! -z "$@" ]]; then
+    warn "$this: unrecognized argument $1 for 'reset' subcommand"
+    printUsage
+    exit 2
+  fi
+
+  git checkout master && git branch -D $CURRENT ||
+    die "Unable to close the review branch $CURRENT"
+}
+
 
 if ! no_changes; then
-  die "You have local changes. Please do something with them before using $0"
+  die "You have local changes. Please do something with them before using $this"
 fi
 
 $GIT svn info >/dev/null 2>/dev/null &&
-  die "$0 does not support git-svn repositories."
+  die "$this does not support git-svn repositories."
 
-LOG=$($GIT log --pretty="format:%s" origin/master..HEAD)
-CHANGESETS=$($GIT rev-list origin/master..HEAD | wc -l)
-CHANGESETS=${CHANGESETS//[[:space:]]}
+while true; do
+  arg=$1
+  shift
+  test -z "$arg" && break;
 
-if [[ "$CHANGESETS" == "0" ]]; then
-  die "You have no changes to review. Are you on the right branch?"
-elif [[ "$CHANGESETS" != "1" ]]; then
-  die "You have $CHANGESETS changes, but you should only push one at a time. Did you forget to squash your commits?"
-fi
+  case $arg
+  in
+    -e | --explain | --dry-run)
+      echo "$this: using explain-only mode"
+      explain=true
+      verbose=true
+      run=false
+      ;;
+    -v | --verbose)
+      verbose=true
+      ;;
+    -q | --quiet)
+      verbose=false
+      ;;
+    -h | --help)
+      printUsage
+      exit
+      ;;
+    start)
+      startReview $1
+      exit
+      ;;
+    reset)
+      resetReview $@
+      exit
+      ;;
+    push)
+      pushReview $1
+      exit
+      ;;
+    *)
+      warn "$this: unrecognized option or subcommand $arg"
+      printUsage
+      exit 2
+      ;;
+  esac
+done
 
-if [[ "$change" != "" ]]; then
-  change_args="origin HEAD:refs/changes/$change"
-fi
-
-git push $change_args ||
-  die "Could not push your changes for review. Perhaps you need to update first?"
-
-if [[ "$CURRENT" == "master" ]]; then
-  git reset --hard origin/master ||
-    die "Could not reset your master branch to origin/master."
-fi
-
-if [[ "$run" == true ]]; then
-  if [[ "$CURRENT" == "master" ]]; then
-    good "Successfully pushed '$LOG' for review and reset master"
-  else
-    good "Successfully pushed '$LOG' for review"
-  fi
-fi
+# no subcommand given
+printShortUsage
+exit 2
