Put in a whole bunch of error messages.

diff --git a/bin/hack b/bin/hack
--- a/bin/hack
+++ b/bin/hack
@@ -1,4 +1,8 @@
 #!/bin/sh
+
+. git-sh-setup
+require_work_tree
+
 CURRENT=$(git symbolic-ref -q HEAD || git rev-parse HEAD)
 CURRENT=${CURRENT#refs/heads/}
 
@@ -46,13 +50,24 @@ done
 GIT=`which git`
 
 git() {
-  test "$verbose" = true && echo "+ git $@"
-  test "$run"     = true && eval "$GIT $@"
+  if [[ "$verbose" == true ]]; then
+    echo "+ git $@"
+  fi
+
+  if [[ "$run" == true ]]; then
+    eval "$GIT $@"
+  fi
 }
 
 no_changes () {
 	$GIT diff-index --quiet --cached HEAD -- &&
 	$GIT diff-files --quiet
+}
+
+check_stash() {
+  if [[ "$stashed" == true ]]; then
+    echo "Your stashed changes were not applied because an error occurred. Don't panic. They are not lost. Look for them in \"git stash list\"."
+  fi
 }
 
 # initial state
@@ -65,8 +80,11 @@ fi
 if no_changes; then
   stashed=false
 else
-  git stash
+  git stash ||
+    die "Could not stash your local changes. Something must be really wrong."
   stashed=true
+
+  trap 'check_stash' EXIT
 fi
 
 REMOTE=`$GIT config branch.$CURRENT.remote`
@@ -84,7 +102,8 @@ fi
 TRACK_BRANCH=${TRACK/refs\/heads\//}
 
 if [[ "$CURRENT" != "$TRACK_BRANCH" ]]; then
-  git checkout $TRACK_BRANCH
+  git checkout $TRACK_BRANCH ||
+    die "Could not switch to $TRACK_BRANCH. Nothing has been changed yet."
 fi
 
 $GIT svn info >/dev/null 2>/dev/null
@@ -95,17 +114,24 @@ else
 fi
 
 if [[ "$TYPE" == "git-svn" ]]; then
-  git svn rebase
+  git svn rebase ||
+    die "Could not complete the rebase from the upstream Subversion server."
 else
-  git fetch $REMOTE
-  git rebase $REMOTE/$TRACK_BRANCH
+  git fetch $REMOTE ||
+    die "Could not fetch updates from $REMOTE. Check your network connection."
+  git rebase $REMOTE/$TRACK_BRANCH ||
+    die "Could not rebase against $REMOTE/$TRACK_BRANCH. You may need to resolve conflicts."
 fi
 
 if [[ "$CURRENT" != "$TRACK_BRANCH" ]]; then
-  git checkout $CURRENT
-  git rebase $TRACK_BRANCH
+  git checkout $CURRENT ||
+    die "Could not switch back to $CURRENT."
+  git rebase $TRACK_BRANCH ||
+    die "Could not rebase against $TRACK_BRANCH. You may need to resolve conflicts."
 fi
 
 if [[ "$stashed" == true ]]; then
-  git stash apply
+  git stash apply ||
+    die "Could not apply your stashed changes over the updates."
+  stashed=false
 fi
