Add some color to make it obvious what's good an what's bad.

diff --git a/bin/hack b/bin/hack
--- a/bin/hack
+++ b/bin/hack
@@ -44,11 +44,31 @@ for arg in "$@"; do
   esac
 done
 
+# colors
+RED="\033[0;31m"
+YELLOW="\033[1;33m"
+GREEN="\033[0;32m"
+NO_COLOR="\033[0m"
+
+die() {
+  echo "${RED}${@}${NO_COLOR}"
+  exit 1
+}
+
+warn() {
+  echo "${YELLOW}${@}${NO_COLOR}"
+}
+
+good() {
+  echo "${GREEN}${@}${NO_COLOR}"
+}
+
+#git stuff
 GIT=`which git`
 
 git() {
   if [[ "$verbose" == true ]]; then
-    echo "+ git $@"
+    echo "+ ${GREEN}git $@${NO_COLOR}"
   fi
 
   if [[ "$run" == true ]]; then
@@ -61,14 +81,9 @@ no_changes () {
 	$GIT diff-files --quiet
 }
 
-die() {
-  echo $@
-  exit 1
-}
-
 check_stash() {
   if [[ "$stashed" == true ]]; then
-    echo "Your stashed changes were not applied because an error occurred. Don't panic. They are not lost. Look for them in \"git stash list\"."
+    warn "Your stashed changes were not applied because an error occurred. Don't panic. They are not lost. Look for them in \"git stash list\"."
   fi
 }
 
@@ -137,3 +152,5 @@ if [[ "$stashed" == true ]]; then
     die "Could not apply your stashed changes over the updates."
   stashed=false
 fi
+
+good "Successfully updated `basename $PWD`"
